version: "3"
services:
  database:
    image: mysql:5.7
    networks:
      - my_net
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample

networks:
  my_net: